name: Build and deploy Node.js app to Azure Web App - lkdevbackendfront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and fix vulnerabilities
      - name: Install dependencies and fix issues
        run: |
          npm install
          npm audit fix || true  # Fix non-breaking issues
          npm audit fix --force || true  # Force fix breaking changes

      # Step 4: Build the project
      - name: Build the project
        run: |
          npm run build --if-present

      # Step 5: Run tests (optional, skip if not needed)
      - name: Run tests
        run: |
          npm test -- --passWithNoTests

      # Step 6: Zip the build folder
      - name: Zip artifact for deployment
        run: zip -r release.zip build/

      # Step 7: Upload the artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Step 1: Download the artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip -d app

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Step 4: Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lkdevbackendfront'
          slot-name: 'Production'
          package: ./app
