name: Build and deploy Node.js app to Azure Web App - lkdevbackendfront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm install
          npm audit fix || true

      # Step 4: Build the project
      - name: Build the project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build

      # Step 5: Zip the build folder
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip build/

      # Step 6: Upload the artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download the artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Unzip the artifact
      - name: Unzip artifact
        run: unzip release.zip -d build

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B80F29835434413C8CCB278CD259A1A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FF1C097387B41DF9DAECDDB18695207 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5397E4ABC948ABB6FF620DB7962FE1 }}

      # Step 4: Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lkdevbackendfront'
          slot-name: 'Production'
          package: ./app
