name: Build and deploy Node.js app to Azure Web App - lkdevbackendfront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies, build the project, and run tests
      - name: npm install, build, and test
        run: |
          npm install
          npm audit fix --force  # Fix vulnerabilities automatically
          npm run build --if-present
          npm test -- --passWithNoTests

      # Create a zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      # Upload the artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure authentication

    steps:
      # Download the artifact created during the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the downloaded artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B80F29835434413C8CCB278CD259A1A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FF1C097387B41DF9DAECDDB18695207 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5397E4ABC948ABB6FF620DB7962FE1 }}

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lkdevbackendfront'
          slot-name: 'Production'
          package: .
